set -g mouse on
set -g history-limit 100000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g set-clipboard on

bind & kill-window
bind x kill-pane
bind X confirm-before -p "kill session #S? (y/n)" kill-session

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind C command-prompt -p "new session name:" "new-session -s '%%' -c '~'"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'

set -g status-style "bg=default,fg=black"
set -g window-status-style "bg=default,fg=black"
set -g window-status-current-style "bg=default,fg=black,bold"
set -g status-left-style "bg=default,fg=black"
set -g status-right-style "bg=default,fg=black"
set -g message-style "bg=default,fg=black"
