set -g mouse on
set -g history-limit 100000

setw -g mode-keys vi
set -g set-clipboard on

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'pbcopy 2>/dev/null || xclip -selection clipboard -in'
